[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_unflags = -std=gnu++11
build_flags = -std=gnu++2a
lib_deps =
    electroniccats/MPU6050@^1.3.1

[env:native]
platform = native
test_framework = googletest
build_flags =
    -std=gnu++20
    -I include